services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: app-php
    working_dir: /var/www
    volumes:
      - ../backend:/var/www
      - ./php/php.ini:/usr/local/etc/php/php.ini
    expose:
      - 9000

  nginx:
    image: nginx:1.27-alpine
    container_name: app-nginx
    depends_on:
      - app
    ports:
      - 8080:80
    volumes:
      - ../backend:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
