services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: imob-app
    restart: always
    working_dir: /var/www
    volumes:
      - ../:/var/www
    expose:
      - 9000
  nginx:
    image: nginx:1.19-alpine
    container_name: imob-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
